### ISSUE TITLE
That's confusing

### ISSUE THREAD

**Issue by OrangeNote** [Yonderward/Yonderward#4]
@francescosassi I think you need to reset your name and email in git client, otherwise it won't match the GitHub account, but instead appears as an external user. 
Try the following:
`git config --global user.name "francescosassi"`
`git config --global user.email your-email@here`

If you recently committed with the old info, try this to amend the previous commit(s).
`git commit --amend --reset-author`
Anyway I don't think it will work with pushed commits too.

**Comment by francescosassi** [comment]
solved but not retroactive
